// Generated by Tender Prompt. Do not edit.

type JsonPrimitive = string | number | boolean | null;
type JsonValue = JsonPrimitive | { [key: string]: JsonValue } | JsonValue[];
type JsonObject = { [key: string]: JsonValue };

type AnalyticsTrackResult =
	| { ok: true }
	| { ok: false; reasonCode: string; message?: string };

type AnalyticsBinding = {
	invoke(input: {
		method: "track";
		payload: {
			event: string;
			unit?: { type: string; id: string };
			flow?: {
				id: string;
				step: string;
				order: number;
				role: "start" | "milestone" | "activity" | "outcome" | "error";
			};
			properties?: JsonObject;
		};
	}): Promise<AnalyticsTrackResult>;
};

type BindingMethod = (...args: unknown[]) => Promise<unknown>;

type BindingPayload<T extends BindingMethod> = Parameters<T> extends []
	? undefined
	: Parameters<T>[0];

type BindingInvokeInput<T extends object, K extends keyof T & string> =
	BindingPayload<Extract<T[K], BindingMethod>> extends undefined
		? { method: K; payload?: undefined }
		: { method: K; payload: BindingPayload<Extract<T[K], BindingMethod>> };

type BindingHost<T extends object> = {
	invoke<K extends keyof T & string>(
		input: BindingInvokeInput<T, K>
	): ReturnType<Extract<T[K], BindingMethod>>;
};

export type AppEnv = {
	__TP_ANALYTICS: AnalyticsBinding;

};
